/**
 * Created by dinanjanag on 4/10/19.
 */
const ACQUIRE_LEASES = 'ACQUIRE_LEASES';
const ACQUIRE_LEASES_FULFILLED = 'ACQUIRE_LEASES_FULFILLED';
const ACQUIRE_LEASES_REJECTED = 'ACQUIRE_LEASES_REJECTED';
const ACQUIRE_LEASE_INFORMATION = 'ACQUIRE_LEASE_INFORMATION';
const ACQUIRE_LEASE_INFORMATION_FULFILLED = 'ACQUIRE_LEASE_INFORMATION_FULFILLED';
const CLOSE_LEASE_INFORMATION_TABLE = 'CLOSE_LEASE_INFORMATION_TABLE';

export {
  ACQUIRE_LEASES,
  ACQUIRE_LEASES_FULFILLED,
  ACQUIRE_LEASES_REJECTED,
  ACQUIRE_LEASE_INFORMATION,
  ACQUIRE_LEASE_INFORMATION_FULFILLED,
  CLOSE_LEASE_INFORMATION_TABLE,
};